### PR TITLE
Add option to spatially limit the plot

### PR DESCRIPTION
**Pull request by pwcazenave**
Added new option to allow a subset plot to be defined.

### CODE REVIEW

**Comment by pierrrrrrre** [comment]
Thanks for the PR! I added a comment, please check it out.

**Comment by pwcazenave** [comment]
Which else condition? The one in generate_map() or the one in main()?

**Comment by pierrrrrrre** [comment]
The one [L129](https://github.com/pwcazenave/PyGeoIpMap/commit/6faa584d242a2247786e8ef32734e4897f07eb02#diff-ac8bc5dd285845308dd739f5fa72fe72R129).

**Comment by pwcazenave** [comment]
Yes, you're right. It's not needed.

**Comment by pierrrrrrre** [comment]
Can you make the needed changes and re-submit a Merge Request?

Thanks!

On Mon, Jun 15, 2015 at 5:01 PM, Pierre Cazenave <notifications@github.com>
wrote:

> Yes, you're right. It's not needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pierrrrrrre/PyGeoIpMap/pull/7#issuecomment-111985327>.
>



-- 
Pierre Equoy

**Pull request closed without merging**
